### ISSUE TITLE
Automate installing of app store apps with 'mas' ?

### ISSUE THREAD

**Issue by adamchainz** [adamchainz/mac-ansible#1]
https://github.com/mas-cli/mas

I only use a few app store apps, could still be useful.

**Comment by adamchainz** [comment]
Meh can't be bothered

**Comment by conatus** [comment]
If you ever can be bothered, I've now done this.

https://github.com/conatus/mac-ansible/blob/master/roles/mac/tasks/installs.yml#L56-L106

Inspired by https://github.com/geerlingguy/ansible-role-mas but a little more minimalist.

**Comment by adamchainz** [comment]
Thanks for info
