### ISSUE TITLE
Allow Graceful Failure When Plist Key Does Not Exist

### ISSUE THREAD

**Issue by conatus** [adamchainz/mac-ansible#2]
Thanks very much for this work, it is excellent.

Right now using the iTerm2 settings setup doesn't quite work. 

This is because the Ansible extension tries to read the setting before it makes any unneccessary changes using `defaults read` - perfectly sensible. However in the case of trying to set up `PrefsCustomFolder` in `com.googlecode.iterm2` for the first time because this key doesn't exist then it fails.

Under the hood:
```
jacques:mac-ansible alex$ defaults read com.googlecode.iterm2 PrefsCustomFolder
2018-12-30 08:40:08.253 defaults[25584:599521]
The domain/default pair of (com.googlecode.iterm2, PrefsCustomFolder) does not exist
```

Work around for the moment: write `PrefsCustomFolder` manually for the first run through.

Unclear to me what the correct first run behaviour should be: I guess it should be set the key and value in this case without further checks? However this might result in error in writing keys and values that don't exist and are wrongly spelt and so on. Happy to fix this with a quick steer.

**Comment by adamchainz** [comment]
Following discussion in #3 this should go upstream since #4 moved to the upstream ansible `osx_defaults` module.
